### ISSUE TITLE
Is there a community channel?

### ISSUE THREAD

**Issue by lidorcg** [stevedekorte/ioWasm#1]
Hi Steve,

Recently I came across Io (it was mentioned in "The joy of clojure") and its elegance amazed me.

I currentntly working on some adjacent issues to what I believe led the core design decisions for Io and I immediately wanted to discuss them with you.

Does Io has some community channel (slack / discord)? I think it really deserves a place to discuss and develop its core ideas and use cases

**Comment by stevedekorte** [comment]
There is a slack, but I don’t check it often. Want to connect on twitter? I’m @stevedekorte

**Comment by lidorcg** [comment]
Sure, if that's your preferred way 🙂
