### ISSUE TITLE
IO WASM as a Library?

### ISSUE THREAD

**Issue by pouyakary** [stevedekorte/ioWasm#2]
I like IO a lot. It's one of the most beautiful languages ever and it was always a shame that I couldn't use it. Now that I see you have the WASM version working it is making me really hopeful. Imagine if you had a WASI build that could run independent of architecture anywhere. Or IO as an npm app that you could install as easily as `npm i -g iolang`. A visual studio code notebook and so on... It could be so awesome.

**Comment by stevedekorte** [comment]
Hi Pouya, thanks for the kind words about Io. I like the ideas you mentioned and would welcome any patches for those. I'd also like to work on a transparent bridge between Io and the DOM when time permits. Proper coroutines inside web apps would be a big improvement over JS async/await.

**Comment by pouyakary** [comment]
You're very welcome and yeah that is definitely true. I have very little information on how it works and the internals, but hopefully if time lets me, I would love see if I can isolate it.
